  postman:
  image: postman/newman:alpine
  container_name: postmanTests
  command:
    run Postman_Assignment.postman_collection.json
    --environment==Gorest.postman_environment.json -k
    -r cli,json
    --reporter-json-export="Postman/Postman_Assignment.postman_collection.json"
  volumes:
    - ./Postman:/etc/newman
  depends_on:
    - "api"
    - "db"
  networks:
    - app_network